### ISSUE TITLE
please add (permissive.. short...) license

### ISSUE THREAD

**Issue by a-detiste** [ZeroPointEnergy/smacshim#1]

**Comment by ZeroPointEnergy** [comment]
Added an MIT license. Hope that is fine.

I'm not sure how useful this couple lines of code are. It let me play the Linux SMAC version with modern builds of SDL1, but it did not work for some others who tried it.

**Comment by twolife** [comment]
this code is pretty helpful, not only it works for SMAC, but it also allows to run the old ports of Descent 3 & Kohan :-)

**Comment by a-detiste** [comment]
Maybe it could get included in sdl12-compat to build a special fake sdl1 for these games that would not need a ld_peload hack.

(sdl12-compat is already a _nice_ big hack in itself)

**Comment by a-detiste** [comment]
> modern builds of SDL1

Here I don't know if you are talking about the real sdl1 or sdl12-compat

**Comment by ZeroPointEnergy** [comment]
I was using a real SDL1. Gentoo still has a version in their repos. I wasn't even aware of sdl12-compat, but that looks like it would be the ideal place to add this code, I agree.

**Comment by ZeroPointEnergy** [comment]
I just had a look at the ebuild and it is indeed sdl12-compat, the package is just not named that way :-)

**Comment by a-detiste** [comment]
sdl12-compat even does weird magic depending on the exécutable name. It's defenitively worth a read.

**Comment by a-detiste** [comment]
Thanks for licensing
